# An example of ClusterConfig showing nodegroups with spot instances
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bomb
  region: us-west-2
  version: "1.19"

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

nodeGroups:
  - name: m5-spot
    minSize: 1
    maxSize: 10
    instanceType: mixed
    desiredCapacity: 2
    volumeSize: 20
    volumeEncrypted: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    privateNetworking: true
    availabilityZones: ["us-west-2b", "us-west-2d"]
    instancesDistribution:
      onDemandPercentageAboveBaseCapacity: 0
      maxPrice: 0.062
      instanceTypes:
        - m5.large
