apiVersion: v1
kind: LimitRange
metadata:
  name: prom-range
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
