apiVersion: batch/v1
kind: Job
metadata:
  name: printenv-job
spec:
  template:
    spec:
      restartPolicy: Never
      # serviceAccountName: iam-secrets-manager-ro
      initContainers:
        - name: secrets-init
          image: doitintl/secrets-init:latest
          command:
            - sh
          args:
            - -c
            - "cp /secrets-init /app/bin/"
          volumeMounts:
          - mountPath: /app/bin
            name: secrets-init-volume
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      containers:
      - image: alpine:3
        name: print-env
        env:
          - name: AWS_REGION
            value: us-west-2
          - name: TOP_SECRET
            value: arn:aws:secretsmanager:us-west-2:906364353610:secret:topsecret-eFOE59
        command:
          - /app/bin/secrets-init
        args:
          - sh
          - -c
          - 'echo $TOP_SECRET'
        volumeMounts:
        - mountPath: /app/bin
          name: secrets-init-volume
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: secrets-init-volume
        emptyDir:
          sizeLimit: 50Mi